### ISSUE TITLE
deformable linear objects 

### ISSUE THREAD

**Issue by unishuai** [Mingrui-Yu/DLO_planning_2#1]
Hello,

  I hope this message finds you well. I have been studying your paper "Generalizable whole-body global manipulation of deformable linear objects by dual-arm robot in 3-D constrained environments". I am particularly interested in the soft-body model you implemented for deformable linear objects (DLOs) .
  I believe this is one of the best articles on flexible cable manipulation!!!!
  I noticed that the URDF file in the project only contains the robot model, and I couldn't find the soft-body model file. Where can I obtain the soft-body model?
Thank you!

**Comment by Mingrui-Yu** [comment]
Thank you for your interest and recognition. Regarding your question, there is no URDF file for the cable. In the planning, we model the DLO using the discrete elastic rod model, which is implemented in C++. In the Unity simulation, we use the Obi package, which is included in the Unity project.

**Comment by unishuai** [comment]
Thanks again for your reply!
